### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by ccloveaa** [egyptianbman/docker-centos-nginx-php#4]
how can I config https server? I tried many times, but still can't work.

`    server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  www.angelvcpe.cn;
        root         /data/www/angelvcpe.cn;

        ssl_certificate "/etc/nginx/ssls/angelvcpe.cn.pem";
        ssl_certificate_key "/etc/nginx/ssls/angelvcpe.cn.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }`

`server {

    listen 443; 
    # ssl http2;
	listen 80;
	ssl on;
    
    ssl_certificate   "/data/www/ssls/wildcard.angelvcpe.cn.pem";
    ssl_certificate_key  "/data/www/ssls/wildcard.angelvcpe.cn.key";
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    
   

    server_name www.angelvcpe.cn angelvcpe.cn;

    location / {
        root   /data/www/angelvcpe.cn;
        index index.php index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location ~ ^.+\.php {

        root           html;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME /data/www/angelvcpe.cn$fastcgi_script_name;
        include        fastcgi_params;
        }

}`

tried to use above config, but not working.

**Comment by egyptianbman** [comment]
Have you considered using https://github.com/jwilder/nginx-proxy with https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion container? They work really well and automatically handle fetching, authenticating, etc. SSL certs via LetsEncrypt.

**Comment by ccloveaa** [comment]
I found the latest tag just expose 80 port, is there any reason or it's a bug?

**Comment by egyptianbman** [comment]
It's not a bug. The intention was for this container to be used with the nginx-proxy, allowing you to run multiple hosts on the same machine. Exposing 443 isn't necessary since you have a proxy that can manage the handshake upstream.
